### ISSUE TITLE
Unable to use certain commands without sudo

### ISSUE THREAD

**Issue by maxrugen** [maxrugen/hue-dash-switch#5]
Running `npm run registerUser` and `node app.js` without `sudo` priviledges outputs the following error messages while using `sudo` with both commands works just fine.

```
$ npm run registerUser

> hue-dash-switch@0.1.0 registerUser /Users/maxrugen/Developer/hue-dash-switch
> node registerUser.js

{ Api Error: link button not pressed
    at checkForError (/Users/maxrugen/Developer/hue-dash-switch/node_modules/node-hue-api/hue-api/httpPromise.js:96:11)
    at /Users/maxrugen/Developer/hue-dash-switch/node_modules/node-hue-api/hue-api/httpPromise.js:144:18
    at _fulfilled (/Users/maxrugen/Developer/hue-dash-switch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/maxrugen/Developer/hue-dash-switch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/maxrugen/Developer/hue-dash-switch/node_modules/q/q.js:796:13)
    at /Users/maxrugen/Developer/hue-dash-switch/node_modules/q/q.js:604:44
    at runSingle (/Users/maxrugen/Developer/hue-dash-switch/node_modules/q/q.js:137:13)
    at flush (/Users/maxrugen/Developer/hue-dash-switch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) message: 'link button not pressed', type: 101 }
```

and 

```
$ node app.js
Error: (cannot open BPF device) /dev/bpf0: Permission denied
    at new PcapSession (/Users/maxrugen/Developer/hue-dash-switch/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/Users/maxrugen/Developer/hue-dash-switch/node_modules/pcap/pcap.js:123:12)
    at create_session (/Users/maxrugen/Developer/hue-dash-switch/node_modules/node-dash-button/index.js:24:28)
    at register (/Users/maxrugen/Developer/hue-dash-switch/node_modules/node-dash-button/index.js:47:24)
    at Object.<anonymous> (/Users/maxrugen/Developer/hue-dash-switch/app.js:8:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'
/Users/maxrugen/Developer/hue-dash-switch/node_modules/node-dash-button/index.js:28
        throw new Error('Error: No devices to listen');
        ^

Error: Error: No devices to listen
    at create_session (/Users/maxrugen/Developer/hue-dash-switch/node_modules/node-dash-button/index.js:28:15)
    at register (/Users/maxrugen/Developer/hue-dash-switch/node_modules/node-dash-button/index.js:47:24)
    at Object.<anonymous> (/Users/maxrugen/Developer/hue-dash-switch/app.js:8:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
```

**Comment by maxrugen** [comment]
Hotfixed with 62c3540, still not quite sure why this issue is being caused again.
